import React, { useState, useEffect } from 'react';
import { Filter, Eye, X, Activity, BrainCircuit, Clock } from 'lucide-react';
import StatusBadge from '../../components/shared/StatusBadge';
import LoadingState from '../../components/shared/LoadingState';
import EmptyState from '../../components/shared/EmptyState';
import { useClinicWebSocket } from '../../hooks/useClinicWebSocket';
import { api } from '../../services/api';

export default function NursePredictions() {
  const [predictions, setPredictions] = useState([]);
  const [selectedPrediction, setSelectedPrediction] = useState(null);
  const [loading, setLoading] = useState(true);
  
  // Filters
  const [filterModel, setFilterModel] = useState('All');
  const [filterType, setFilterType] = useState('All');
  const [filterStatus, setFilterStatus] = useState('All');

  const { lastEvent } = useClinicWebSocket();

  const fetchData = async () => {
    try {
      const res = await api.get('/nurse/predictions').catch(() => []);
      const data = Array.isArray(res) ? res : (res.data || []);
      setPredictions(data);
      if (data.length > 0 && !selectedPrediction) {
        setSelectedPrediction(data[0]);
      }
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [lastEvent]);

  if (loading) return <LoadingState message="Loading Live Predictions..." />;

  const filteredPredictions = predictions.filter(p => {
    if (filterModel !== 'All' && p.model !== filterModel) return false;
    if (filterType !== 'All' && p.type !== filterType) return false;
    if (filterStatus !== 'All' && p.status !== filterStatus) return false;
    return true;
  });

  const uniqueModels = ['All', ...new Set(predictions.map(p => p.model).filter(Boolean))];
  const uniqueTypes = ['All', ...new Set(predictions.map(p => p.type).filter(Boolean))];
  const uniqueStatuses = ['All', ...new Set(predictions.map(p => p.status).filter(Boolean))];

  return (
    <div className="p-6 h-full flex flex-col space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Live ML Predictions</h1>
        <p className="text-gray-500">Current predictions generated by ClinicFlow models.</p>
      </div>

      {/* Filters */}
      <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-100 flex flex-wrap gap-4 items-center">
        <Filter className="w-5 h-5 text-gray-400" />
        <select 
          className="border-gray-300 rounded-md shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
          value={filterModel}
          onChange={(e) => setFilterModel(e.target.value)}
        >
          {uniqueModels.map(m => <option key={m} value={m}>{m === 'All' ? 'All Models' : m}</option>)}
        </select>
        
        <select 
          className="border-gray-300 rounded-md shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
          value={filterType}
          onChange={(e) => setFilterType(e.target.value)}
        >
          {uniqueTypes.map(t => <option key={t} value={t}>{t === 'All' ? 'All Types' : t}</option>)}
        </select>

        <select 
          className="border-gray-300 rounded-md shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
          value={filterStatus}
          onChange={(e) => setFilterStatus(e.target.value)}
        >
          {uniqueStatuses.map(s => <option key={s} value={s}>{s === 'All' ? 'All Statuses' : s}</option>)}
        </select>
      </div>

      <div className="flex flex-col lg:flex-row gap-6 flex-1 min-h-0 overflow-hidden">
        {/* Table */}
        <div className={`bg-white border border-gray-200 rounded-lg shadow-sm overflow-hidden flex flex-col transition-all ${selectedPrediction ? 'lg:w-2/3' : 'w-full'}`}>
          <div className="overflow-x-auto flex-1">
            {filteredPredictions.length > 0 ? (
              <table className="w-full text-left text-sm">
                <thead className="bg-gray-50 text-gray-600 sticky top-0">
                  <tr>
                    <th className="px-6 py-3 font-medium">Prediction Type</th>
                    <th className="px-6 py-3 font-medium">Prediction</th>
                    <th className="px-6 py-3 font-medium">Model</th>
                    <th className="px-6 py-3 font-medium">Version</th>
                    <th className="px-6 py-3 font-medium">Timestamp</th>
                    <th className="px-6 py-3 font-medium">Status</th>
                    <th className="px-6 py-3 font-medium">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {filteredPredictions.map((pred, i) => (
                    <tr key={i} className={`hover:bg-gray-50/50 ${selectedPrediction?.id === pred.id ? 'bg-indigo-50' : ''}`}>
                      <td className="px-6 py-4 font-medium text-gray-900">{pred.type || "N/A"}</td>
                      <td className="px-6 py-4 font-mono text-indigo-600">{pred.prediction || "N/A"}</td>
                      <td className="px-6 py-4 text-gray-600">{pred.model || "N/A"}</td>
                      <td className="px-6 py-4 text-gray-500">{pred.modelVersion || "N/A"}</td>
                      <td className="px-6 py-4 text-gray-500 whitespace-nowrap">{pred.timestamp || "N/A"}</td>
                      <td className="px-6 py-4">
                        <StatusBadge status={pred.status === 'Applied' ? 'success' : pred.status === 'Pending' ? 'warning' : 'gray'}>
                          {pred.status || "UNKNOWN"}
                        </StatusBadge>
                      </td>
                      <td className="px-6 py-4">
                        <button 
                          onClick={() => setSelectedPrediction(pred)}
                          className="text-indigo-600 hover:text-indigo-900"
                        >
                          <Eye className="w-5 h-5" />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : (
              <div className="p-10 h-full flex items-center justify-center">
                <EmptyState title="NO PREDICTIONS" description="No predictions match the current filters." />
              </div>
            )}
          </div>
        </div>

        {/* Prediction Detail Sidebar */}
        {selectedPrediction && (
          <div className="lg:w-1/3 bg-white border border-gray-200 rounded-lg shadow-sm flex flex-col overflow-hidden">
            <div className="px-6 py-4 border-b border-gray-100 bg-gray-50 flex justify-between items-center">
              <h2 className="text-lg font-semibold text-gray-800 flex items-center">
                <BrainCircuit className="w-5 h-5 mr-2 text-indigo-600" /> Detail
              </h2>
              <button onClick={() => setSelectedPrediction(null)} className="text-gray-400 hover:text-gray-600">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto space-y-6">
              <div>
                <h3 className="text-xl font-bold text-gray-900 mb-1">{selectedPrediction.type || "Unknown Type"}</h3>
                <p className="text-indigo-600 font-mono text-lg">{selectedPrediction.prediction || "N/A"}</p>
              </div>

              <div className="space-y-3">
                <div className="flex justify-between border-b pb-2">
                  <span className="text-sm text-gray-500 flex items-center"><Activity className="w-4 h-4 mr-1"/> Model</span>
                  <span className="font-medium text-gray-900">{selectedPrediction.model || "N/A"}</span>
                </div>
                <div className="flex justify-between border-b pb-2">
                  <span className="text-sm text-gray-500 flex items-center"><Clock className="w-4 h-4 mr-1"/> Timestamp</span>
                  <span className="font-medium text-gray-900">{selectedPrediction.timestamp || "N/A"}</span>
                </div>
                <div className="flex justify-between border-b pb-2">
                  <span className="text-sm text-gray-500">Explanation</span>
                  <span className="font-medium text-gray-900">
                    {selectedPrediction.explanationAvailable ? (
                      <span className="text-green-600 flex items-center">Available</span>
                    ) : (
                      <span className="text-gray-400">Unavailable</span>
                    )}
                  </span>
                </div>
              </div>

              <div>
                <h4 className="text-sm font-semibold text-gray-700 mb-2">Input Context</h4>
                <div className="bg-gray-50 p-3 rounded-md text-sm font-mono text-gray-600 break-words whitespace-pre-wrap">
                  {selectedPrediction.inputContext ? JSON.stringify(selectedPrediction.inputContext, null, 2) : "DATA UNAVAILABLE"}
                </div>
              </div>

              <div>
                <h4 className="text-sm font-semibold text-gray-700 mb-2">Features Used</h4>
                <div className="flex flex-wrap gap-2">
                  {selectedPrediction.featuresUsed && selectedPrediction.featuresUsed.length > 0 ? (
                    selectedPrediction.featuresUsed.map((feat, idx) => (
                      <span key={idx} className="px-2 py-1 bg-indigo-50 text-indigo-700 border border-indigo-100 rounded text-xs">
                        {feat}
                      </span>
                    ))
                  ) : (
                    <span className="text-gray-400 text-sm">DATA UNAVAILABLE</span>
                  )}
                </div>
              </div>

            </div>
          </div>
        )}
      </div>
    </div>
  );
}
